version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/nextjs-aws-test

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start-nextjs.sh
      timeout: 60
      runas: ubuntu
